### ISSUE TITLE
A bit of padding for code snippets

### ISSUE THREAD

**Issue by cryptomilk** [jl-wynen/that_style#2]
Hello,

thank you very much for this nice and modern style!

I've started to use it for cmocka (https://api.cmocka.org/) and libssh.org will follow soon. I think it would be nice if the code snippets box would get a little bit of padding of the dark grey box around the text.

Maybe worth a try :-)

**Comment by jl-wynen** [comment]
Hi,

thanks, glad to hear that :smiley:

You have a good point. I tried that a while ago but it doesn't play nice with line numbers so I didn't put it in. But I just pushed a change that adds a little padding around code snippets and removes the extra background colour for line numbers. Hope this looks better!

**Comment by cryptomilk** [comment]
That looks better, thanks. https://api.libssh.org/ also uses that_style now!

**Comment by jl-wynen** [comment]
Love to help!
